/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.event.MenuEvent;
import menu.menuEvent;

/**
 *
 * @author User
 */
public class kalkulatorvVew extends javax.swing.JFrame {

    /**
     * Creates new form kalkulatorvVew
     */
     private String nama = "";
    
    public kalkulatorvVew() {
        
        initComponents();
        menu1.setEvent(new menuEvent(){
            
            @Override
            public void selected(int index,int subIndex)
                {
                     nama = menu1.getItemsName(index, subIndex);
                     
                     selectedclick(nama); 
                     
                      
                }
           
        });
  
    }
    
    public void selectedclick(String nama)
    {
        
         if(nama.equalsIgnoreCase("Kecepatan Tempuh"))   
         {  
              RumusKecepatanTempuh KecepatanTempuh =  new  RumusKecepatanTempuh();
              this.dispose();
              KecepatanTempuh.setVisible(true);
         }
         else if(nama.equalsIgnoreCase("Headway"))
         {
               RumusHeadway  Headway =   new RumusHeadway();
               this.dispose();
               Headway.setVisible(true);
                        
         }
         else if(nama.equalsIgnoreCase("Jumlah Kendaraan"))
         {
             RumusJumlahKendaraan  JumlahKendaraan = new RumusJumlahKendaraan();
             this.dispose();
             JumlahKendaraan.setVisible(true);
             
         }
         else if(nama.equalsIgnoreCase("Credit"))
         {
             Credit kredit  = new Credit();
             this.dispose();
             kredit.setVisible(true);
         }else if(nama.equalsIgnoreCase("Load Factory"))
         {
             RumusLoadFactor LoadFactor = new RumusLoadFactor();
             this.dispose();
             LoadFactor.setVisible(true);
         }
         
    }
    
    public void clearText()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        slideBar = new javax.swing.JPanel();
        slideBarIcon = new javax.swing.JLabel();
        menu1 = new menu.menu();
        header = new javax.swing.JPanel();
        kalkulatorJudul = new javax.swing.JLabel();
        identitasHeader = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        npmLabel = new javax.swing.JLabel();
        papanKalkulator = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        slideBarIcon1 = new javax.swing.JLabel();
        slideBarIcon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideBar.setBackground(new java.awt.Color(204, 204, 0));
        slideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideBarIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slideBarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        slideBarIcon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        slideBarIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideBarIconMouseClicked(evt);
            }
        });
        slideBar.add(slideBarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 41));

        menu1.setBackground(new java.awt.Color(255, 0, 51));
        menu1.setForeground(new java.awt.Color(255, 51, 51));
        slideBar.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, -1));

        jPanel1.add(slideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 170, 440));

        header.setBackground(new java.awt.Color(255, 204, 51));

        kalkulatorJudul.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        kalkulatorJudul.setForeground(new java.awt.Color(0, 0, 0));
        kalkulatorJudul.setText("KALKULATOR RUMUS");

        identitasHeader.setBackground(new java.awt.Color(255, 204, 51));

        namaLabel.setBackground(new java.awt.Color(0, 0, 0));
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setText("Nama : ");

        npmLabel.setBackground(new java.awt.Color(0, 0, 0));
        npmLabel.setForeground(new java.awt.Color(0, 0, 0));
        npmLabel.setText("EUNIKE M.MACPAL");

        javax.swing.GroupLayout identitasHeaderLayout = new javax.swing.GroupLayout(identitasHeader);
        identitasHeader.setLayout(identitasHeaderLayout);
        identitasHeaderLayout.setHorizontalGroup(
            identitasHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identitasHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(npmLabel)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        identitasHeaderLayout.setVerticalGroup(
            identitasHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identitasHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(identitasHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(npmLabel))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(identitasHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(kalkulatorJudul)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kalkulatorJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(identitasHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 110));

        papanKalkulator.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KALKULATOR RUMUS");

        javax.swing.GroupLayout papanKalkulatorLayout = new javax.swing.GroupLayout(papanKalkulator);
        papanKalkulator.setLayout(papanKalkulatorLayout);
        papanKalkulatorLayout.setHorizontalGroup(
            papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, papanKalkulatorLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        papanKalkulatorLayout.setVerticalGroup(
            papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(papanKalkulatorLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jPanel1.add(papanKalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 440));

        slideBarIcon1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slideBarIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        slideBarIcon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        slideBarIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideBarIcon1MouseClicked(evt);
            }
        });
        jPanel1.add(slideBarIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 40));

        slideBarIcon2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slideBarIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        slideBarIcon2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(slideBarIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x = 164;
    private void slideBarIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideBarIconMouseClicked
        // TODO add your handling code here:
        
        if(x == 164)
        {
            slideBar.setSize(164, 552);
            
            Thread th = new Thread() 
            {
               @Override
               public  void run()
               {
                    try
                    {
                        for(int i = 164; i>= 0;i--)
                        {
                            Thread.sleep(1);
                            slideBar.setSize(i, 552);
                        }
                        
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
                    }
                   
               }
                
            }; th.start();
            x=0;
        }
      
    }//GEN-LAST:event_slideBarIconMouseClicked

    private void slideBarIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideBarIcon1MouseClicked

        if(x == 0)
        {
            slideBar.show();
            slideBar.setSize(x, 552);

            Thread th = new Thread()
            {
                @Override
                public  void run()
                {
                    try
                    {
                        for(int i = 0; i <= x;i++)
                        {
                            Thread.sleep(1);
                            slideBar.setSize(i, 552);

                        }

                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
                    }

                }

            }; th.start();
            x=164;
        }
    }//GEN-LAST:event_slideBarIcon1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulatorvVew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulatorvVew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulatorvVew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulatorvVew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new kalkulatorvVew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JPanel identitasHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kalkulatorJudul;
    private menu.menu menu1;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JPanel papanKalkulator;
    private javax.swing.JPanel slideBar;
    private javax.swing.JLabel slideBarIcon;
    private javax.swing.JLabel slideBarIcon1;
    private javax.swing.JLabel slideBarIcon2;
    // End of variables declaration//GEN-END:variables
}
