/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import menu.menuEvent;
import java.lang.Math;
import Exception.inputKosongException;
import java.math.RoundingMode;
import java.text.DecimalFormat;
/**
 *
 * @author User
 */
public class RumusHeadway extends javax.swing.JFrame {

    /**
     * Creates new form kalkulatorvVew
     */private String  nama = "";
    public RumusHeadway() {
        initComponents();
        HeadWay.setEditable(false);
         menu1.setEvent(new menuEvent(){
            
            @Override
            public void selected(int index,int subIndex)
                {
                     nama = menu1.getItemsName(index, subIndex);
                     
                     selectedclick(nama); 
                     
                      
                }
           
        });
         clearText();
    }
    
     public void selectedclick(String nama)
    {
        
         if(nama.equalsIgnoreCase("Kecepatan Tempuh"))   
         {  
              RumusKecepatanTempuh KecepatanTempuh =  new  RumusKecepatanTempuh();
              this.dispose();
              KecepatanTempuh.setVisible(true);
         }
         else if(nama.equalsIgnoreCase("Jumlah Kendaraan"))
         {
             RumusJumlahKendaraan  JumlahKendaraan = new RumusJumlahKendaraan();
             this.dispose();
             JumlahKendaraan.setVisible(true);
             
         }
         else if(nama.equalsIgnoreCase("Credit"))
         {
             Credit kredit  = new Credit();
             this.dispose();
             kredit.setVisible(true);
         }else if(nama.equalsIgnoreCase("Load Factory"))
         {
             RumusLoadFactor LoadFactor = new RumusLoadFactor();
             this.dispose();
             LoadFactor.setVisible(true);
         }
         
    }

     public void clearText()
     {
          HeadWay.setText("");
          KapasitasKendaraanInput.setText("");
          LoadFactorinput.setText("");
     }
     
     public void InputKosongException() throws inputKosongException
      {
          if( KapasitasKendaraanInput.getText().isEmpty() && LoadFactorinput.getText().isEmpty())
          {
              throw new  inputKosongException();
          }
     
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        slideBar = new javax.swing.JPanel();
        slideBarIcon = new javax.swing.JLabel();
        menu1 = new menu.menu();
        header = new javax.swing.JPanel();
        kalkulatorJudul = new javax.swing.JLabel();
        identitasHeader = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        npmLabel = new javax.swing.JLabel();
        papanKalkulator = new javax.swing.JPanel();
        HeadWayLabel = new javax.swing.JLabel();
        T1Label = new javax.swing.JLabel();
        T2Label = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        KapasitasKendaraanInput = new javax.swing.JTextField();
        LoadFactorinput = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();
        HeadWay = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        JumlahPenumpanginput = new javax.swing.JTextField();
        T2Label1 = new javax.swing.JLabel();
        T2Label2 = new javax.swing.JLabel();
        slideBarIcon1 = new javax.swing.JLabel();
        slideBarIcon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideBar.setBackground(new java.awt.Color(204, 204, 0));
        slideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slideBarIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slideBarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        slideBarIcon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        slideBarIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideBarIconMouseClicked(evt);
            }
        });
        slideBar.add(slideBarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 41));

        menu1.setBackground(new java.awt.Color(255, 0, 51));
        menu1.setForeground(new java.awt.Color(255, 51, 51));
        slideBar.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, -1));

        jPanel1.add(slideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 170, 440));

        header.setBackground(new java.awt.Color(255, 204, 51));

        kalkulatorJudul.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        kalkulatorJudul.setForeground(new java.awt.Color(0, 0, 0));
        kalkulatorJudul.setText("KALKULATOR RUMUS");

        identitasHeader.setBackground(new java.awt.Color(255, 204, 51));

        namaLabel.setBackground(new java.awt.Color(0, 0, 0));
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setText("Nama : ");

        npmLabel.setBackground(new java.awt.Color(0, 0, 0));
        npmLabel.setForeground(new java.awt.Color(0, 0, 0));
        npmLabel.setText("EUNIKE M.MACPAL");

        javax.swing.GroupLayout identitasHeaderLayout = new javax.swing.GroupLayout(identitasHeader);
        identitasHeader.setLayout(identitasHeaderLayout);
        identitasHeaderLayout.setHorizontalGroup(
            identitasHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identitasHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(npmLabel)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        identitasHeaderLayout.setVerticalGroup(
            identitasHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identitasHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(identitasHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(npmLabel))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(identitasHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(kalkulatorJudul)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kalkulatorJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(identitasHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        papanKalkulator.setBackground(new java.awt.Color(255, 204, 0));

        HeadWayLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeadWayLabel.setForeground(new java.awt.Color(0, 0, 0));
        HeadWayLabel.setText("HEADWAY (Menit)");

        T1Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        T1Label.setForeground(new java.awt.Color(0, 0, 0));
        T1Label.setText("Kapasitas Kendaraan (C)");

        T2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        T2Label.setForeground(new java.awt.Color(0, 0, 0));
        T2Label.setText("Load Factor (Lf) ");

        Hasil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hasil.setForeground(new java.awt.Color(0, 0, 0));
        Hasil.setText("HASIL");

        KapasitasKendaraanInput.setBackground(new java.awt.Color(255, 255, 255));
        KapasitasKendaraanInput.setForeground(new java.awt.Color(0, 0, 0));

        LoadFactorinput.setBackground(new java.awt.Color(255, 255, 255));
        LoadFactorinput.setForeground(new java.awt.Color(0, 0, 0));

        Hapus.setBackground(new java.awt.Color(255, 0, 0));
        Hapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Hapus.setForeground(new java.awt.Color(0, 51, 204));
        Hapus.setText("Hapus");
        Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusMouseClicked(evt);
            }
        });
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        HeadWay.setBackground(new java.awt.Color(255, 255, 255));
        HeadWay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeadWay.setForeground(new java.awt.Color(0, 0, 0));
        HeadWay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HeadWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeadWayActionPerformed(evt);
            }
        });

        Hitung.setBackground(new java.awt.Color(102, 255, 0));
        Hitung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Hitung.setForeground(new java.awt.Color(0, 51, 204));
        Hitung.setText("Hitung");
        Hitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HitungMouseClicked(evt);
            }
        });
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        JumlahPenumpanginput.setBackground(new java.awt.Color(255, 255, 255));
        JumlahPenumpanginput.setForeground(new java.awt.Color(0, 0, 0));

        T2Label1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        T2Label1.setForeground(new java.awt.Color(0, 0, 0));
        T2Label1.setText("JumlahPenumpang/Jam (P)");

        T2Label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        T2Label2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout papanKalkulatorLayout = new javax.swing.GroupLayout(papanKalkulator);
        papanKalkulator.setLayout(papanKalkulatorLayout);
        papanKalkulatorLayout.setHorizontalGroup(
            papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(papanKalkulatorLayout.createSequentialGroup()
                .addGroup(papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(papanKalkulatorLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(papanKalkulatorLayout.createSequentialGroup()
                                .addComponent(JumlahPenumpanginput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(T2Label1)
                            .addComponent(T2Label)
                            .addComponent(KapasitasKendaraanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoadFactorinput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T2Label2)
                            .addComponent(T1Label)))
                    .addGroup(papanKalkulatorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hitung))))
                .addGroup(papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(papanKalkulatorLayout.createSequentialGroup()
                        .addComponent(HeadWay, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, papanKalkulatorLayout.createSequentialGroup()
                        .addComponent(Hasil)
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, papanKalkulatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HeadWayLabel)
                .addGap(60, 60, 60))
        );
        papanKalkulatorLayout.setVerticalGroup(
            papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(papanKalkulatorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(HeadWayLabel)
                .addGap(18, 18, 18)
                .addComponent(T1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KapasitasKendaraanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(T2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadFactorinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(T2Label1)
                .addGap(13, 13, 13)
                .addComponent(JumlahPenumpanginput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(T2Label2)
                .addGroup(papanKalkulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(papanKalkulatorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Hitung)
                        .addGap(18, 18, 18)
                        .addComponent(Hapus)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, papanKalkulatorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HeadWay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        jPanel1.add(papanKalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 360, 440));

        slideBarIcon1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slideBarIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        slideBarIcon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        slideBarIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slideBarIcon1MouseClicked(evt);
            }
        });
        jPanel1.add(slideBarIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 40));

        slideBarIcon2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slideBarIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu (1).png"))); // NOI18N
        slideBarIcon2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(slideBarIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x = 164;
    private void slideBarIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideBarIconMouseClicked
        // TODO add your handling code here:
        
        if(x == 164)
        {
            slideBar.setSize(164, 552);
            
            Thread th = new Thread() 
            {
               @Override
               public  void run()
               {
                    try
                    {
                        for(int i = 164; i>= 0;i--)
                        {
                            Thread.sleep(1);
                            slideBar.setSize(i, 552);
                        }
                        
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
                    }
                   
               }
                
            }; th.start();
            x=0;
        }
      
    }//GEN-LAST:event_slideBarIconMouseClicked

    private void slideBarIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slideBarIcon1MouseClicked

        if(x == 0)
        {
            slideBar.show();
            slideBar.setSize(x, 552);

            Thread th = new Thread()
            {
                @Override
                public  void run()
                {
                    try
                    {
                        for(int i = 0; i <= x;i++)
                        {
                            Thread.sleep(1);
                            slideBar.setSize(i, 552);

                        }

                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
                    }

                }

            }; th.start();
            x=164;
        }
    }//GEN-LAST:event_slideBarIcon1MouseClicked

    private void HapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusMouseClicked
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_HapusMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusActionPerformed

    private void HeadWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeadWayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeadWayActionPerformed

    private void HitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HitungMouseClicked
        // TODO add your handling code here:
         double loadfactor,hasil,jumlahpenumpang;
         int kapasitasKendaraan;
        
        try
        {
            InputKosongException();
            
            DecimalFormat df=new DecimalFormat("#.##");
            
            loadfactor = Double.parseDouble(LoadFactorinput.getText());
            jumlahpenumpang =  Double.parseDouble(JumlahPenumpanginput.getText());
             kapasitasKendaraan=  Integer.parseInt(KapasitasKendaraanInput.getText());
            
            hasil = Math.abs((60*  kapasitasKendaraan*loadfactor)/jumlahpenumpang);
            
            HeadWay.setText(df.format(hasil) + " Menit ");    
        }
        catch(inputKosongException e)
        {
             JOptionPane.showMessageDialog(this, e.message());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "INPUTAN HARUS BERUPA ANGKA !");
        }
    }//GEN-LAST:event_HitungMouseClicked

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RumusHeadway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RumusHeadway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RumusHeadway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RumusHeadway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RumusHeadway().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JLabel Hasil;
    private javax.swing.JTextField HeadWay;
    private javax.swing.JLabel HeadWayLabel;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField JumlahPenumpanginput;
    private javax.swing.JTextField KapasitasKendaraanInput;
    private javax.swing.JTextField LoadFactorinput;
    private javax.swing.JLabel T1Label;
    private javax.swing.JLabel T2Label;
    private javax.swing.JLabel T2Label1;
    private javax.swing.JLabel T2Label2;
    private javax.swing.JPanel header;
    private javax.swing.JPanel identitasHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kalkulatorJudul;
    private menu.menu menu1;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JPanel papanKalkulator;
    private javax.swing.JPanel slideBar;
    private javax.swing.JLabel slideBarIcon;
    private javax.swing.JLabel slideBarIcon1;
    private javax.swing.JLabel slideBarIcon2;
    // End of variables declaration//GEN-END:variables
}
